helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls), ]

handler403 = 'main.views.handler403'
handler404 = 'main.views.handler404'
handler500 = 'main.views.handler500'

main/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django_email_verification import urls as email_urls
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.loginUser, name='login'),
    path('create_user/', views.createUser, name='create_user'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logoutUser, name='logout'), 
    path('settings/', views.settings, name="settings"),
    path('delete_user/<str:pk>/', views.deleteUser, name="delete_user"),
    path('change_password/', views.changePassword, name="change_password"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="main/password_reset.html", email_template_name='main/password_reset_email.html'), name="password_reset"),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(template_name="main/password_reset_done.html"), name="password_reset_done"),
    path('reset_password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="main/password_reset_confirm.html"), name="password_reset_confirm"),
    path('reset_password/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="main/password_reset_complete.html"), name="password_reset_complete"),
    path('verify_email/', include(email_urls)),
    path('create_issue/', views.createIssue, name='create_issue'),
    path('update_issue/<str:pk>/', views.updateIssue, name="update_issue"),
    path('delete_issue/<str:pk>/', views.deleteIssue, name="delete_issue"),
    path('archive/', views.archive, name="archive"),
    path('statistics/', views.statistics, name="statistics"),
    path('user_management/', views.userManagement, name="user_management"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Issue(models.Model):
    reporter = models.ForeignKey(User, related_name='reporter', on_delete=models.CASCADE)
    assignee = models.ForeignKey(User, related_name='assignee', on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    deadline = models.DateTimeField()
    solution = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    STATUS = (
        ('to_do', ('Nierozpoczęte')),
        ('in_progress', ('W realizacji')),
        ('testing', ('Testowanie')),
        ('done', ('Ukończone')),
    )

    status = models.CharField(max_length=32, choices=STATUS, default='to_do')

    TYPE = (
        ('fix', ('Błąd')),
        ('bug', ('Usterka')),
        ('service', ('Naprawa')),
        ('error', ('Nieprawidłowe działanie')),
    )

    type = models.CharField(max_length=32, choices=TYPE, default='fix')
    
    def __str__(self):
        return self.title

main/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Issue

class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'Hasło'
        self.fields['password2'].label = 'Potwierdzenie hasła'

    class Meta:
        model = User
        
        for value in ('first_name', 'last_name', 'email'):
            model._meta.get_field(value).blank = False
            model._meta.get_field(value).null = False
        model._meta.get_field('email')._unique = True

        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        labels  = {
            'username':'Login', 
            'first_name':'Imię',
            'last_name':'Nazwisko',
            'email':'Adres e-mail',
            'password1':'Hasło',
            'password2':'Potwierdzenie hasła',
        }


class UpdateUserForm(ModelForm):
    class Meta:
        model = User

        fields = ['email', 'first_name', 'last_name']
        labels  = {
            'email':'Adres e-mail',
            'first_name':'Imię',
            'last_name':'Nazwisko',
        }


class CreateIssueForm(ModelForm):
    class Meta:
        model = Issue
        fields = ['title', 'description', 'deadline', 'status', 'solution', 'type']

main/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group
from .forms import CreateUserForm, UpdateUserForm, CreateIssueForm
from django_email_verification import send_email
from .models import Issue
from .decorators import group_required
import datetime as dt


def index(request):
    return render(request, "main/index.html")


def loginUser(request):
    if not isNowInTimePeriod(dt.time(7,30), dt.time(16,30), dt.datetime.now().time()):
        return render(request, "errors/outside_working_hours.html")

    if request.user.is_authenticated:
        return redirect('dashboard')
    else:
        if request.method == 'POST':
            username = request.POST.get('username').lower()
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('dashboard')
            else:
                try:
                    user = User.objects.get(username=username)

                    if user.is_active == False:
                        messages.error(request, 'Twoje konto jest nieaktywne. Potwierdź je za pomocą wiadomości, którą otrzymałeś na adres e-mail podany administratorowi systemu podczas tworzenia konta.')
                        send_email(user)
                except User.DoesNotExist:
                    messages.error(request, 'Login lub hasło są nieprawidłowe.')

        context = {}
        return render(request, 'main/login.html', context)


@group_required('Administrators', raise_exception=True)
def createUser(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if User.objects.filter(username__iexact=request.POST['username']):
            messages.error(request, 'Użytkownik o tym loginie już istnieje.')
            return redirect('create_user')
        elif User.objects.filter(email__iexact=request.POST['email']):
            messages.error(request, 'Użytkownik połączony z tym adresem e-mail już istnieje.')
            return redirect('create_user')
        elif form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            send_email(user)
            user.save()

            if request.POST['role'] == 'user':
                group = Group.objects.get(name='Users')
            elif request.POST['role'] == 'staff':
                group = Group.objects.get(name='Staff')
            group.user_set.add(user)
            
            username = form.cleaned_data.get('username')
            messages.success(request, f'Konto użytkownika {username} zostało utworzone. Na podany adres e-mail został wysłany link potwierdzający konto.')
            return redirect('create_user')

    context = {'form': form}
    return render(request, "main/create_user.html", context)


@login_required(login_url='login')
def logoutUser(request):
    logout(request)
    messages.success(request, 'Pomyślnie wylogowano użytkownika.')
    return redirect('login')


@login_required(login_url='login')
def dashboard(request):
    if request.user.groups.filter(name='Administrators').exists():
        issues = Issue.objects.exclude(status='done').order_by('deadline').all()
    elif request.user.groups.filter(name='Staff').exists():
        issues = Issue.objects.filter(assignee=request.user).exclude(status='done').order_by('deadline').all()
    elif request.user.groups.filter(name='Users').exists():
        issues = Issue.objects.filter(reporter=request.user).exclude(status='done').order_by('deadline').all()
    
    staff = User.objects.filter(groups__name='Administrators') | User.objects.filter(groups__name='Staff')

    context = {'issues': issues, 'staff': staff}
    return render(request, "main/dashboard.html", context)


@login_required(login_url='login')
def settings(request):
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)

        if form.is_valid():
            messages.success(request, 'Dane użytkownika zostały pomyślnie zmodyfikowane.')
            form.save()
            return redirect('settings')
        else:
            messages.error(request, 'Wystąpił błąd poczas modyfikacji danych użytkownika.')
            return redirect('settings')
    else:
        form = UpdateUserForm(instance=request.user)
        context = {'form': form}
        return render(request, 'main/settings.html', context)


@login_required(login_url='login')
def changePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            messages.success(request, 'Hasło zostało zaktualizowane.')
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('settings')
        else:
            messages.error(request, 'Wystąpił błąd podczas aktualizacji hasła. \
            Obecne hasło jest nieprawidłowe, nowe hasło nie spełnia wymagać lub nowe hasło i jego potwierdzenie nie są identyczne.')
            return redirect('change_password')
    else:
        form = PasswordChangeForm(user=request.user)

        context = {'form': form}
        return render(request, 'main/change_password.html', context)


@login_required(login_url='login')
def deleteUser(request, pk):
    user = User.objects.get(id=pk)
    if user is not None:
        user.delete()
        messages.success(request, 'Użytkownik został pomyślnie usunięty.')
        if request.user.id != user.id:
            return redirect('user_management')
        return redirect('login')
    else:
        messages.error(request, 'Wystąpił błąd podczas usuwania użytkownika.')
        return redirect('settings')


@login_required(login_url='login')
def createIssue(request):
    form = CreateIssueForm()

    if request.method == 'POST':
        form = CreateIssueForm(request.POST)
        if form.is_valid():
            issue = form.save(commit=False)
            issue.reporter = request.user
            issue.save()
            messages.success(request, 'Zgłoszenie zostało pomyślnie utworzone.')
            return redirect('dashboard')

    context = {'form': form}
    return render(request, "main/create_issue.html", context)


@login_required(login_url='login')
def updateIssue(request, pk):
    issue = Issue.objects.get(id=pk)
    print(request.POST)
    if request.method == "POST":
        form = CreateIssueForm(request.POST, instance=issue)
        if form.is_valid():
            if request.user.groups.filter(name='Administrators').exists():
                issue.assignee = User.objects.filter(id=request.POST['assignee']).first()
            form.save()
            messages.success(request, 'Zgłoszenie zostało pomyślnie zmodyfikowane.')
            return redirect('dashboard')

    messages.error(request, 'Wystąpił błąd podczas modyfikacji zgłoszenia.')
    return redirect('dashboard')


@login_required(login_url='login')
def deleteIssue(request, pk):
    issue = Issue.objects.get(id=pk)
    
    if request.method == "POST":
        issue.delete()
        messages.success(request, 'Zgłoszenie zostało pomyślnie usunięte.')
        return redirect('dashboard')

    messages.error(request, 'Wystąpił błąd podczas usuwania zgłoszenia.')
    return redirect('dashboard')


@login_required(login_url='login')
def archive(request):
    if request.user.groups.filter(name='Users').exists():
        issues = issues = Issue.objects.filter(reporter=request.user, status='done').order_by('deadline').all()
    else:
        issues = Issue.objects.filter(status='done').order_by('deadline').all()
    
    staff = User.objects.filter(groups__name='Administrators') | User.objects.filter(groups__name='Staff')

    context = {'issues': issues, 'staff': staff}
    return render(request, "main/archive.html", context)


@group_required('Administrators', raise_exception=True)
def statistics(request):
    undone_count = Issue.objects.exclude(status='done').all().count()
    to_do_count = Issue.objects.filter(status='to_do').all().count()
    in_progress_count = Issue.objects.filter(status='in_progress').all().count()
    testing_count = Issue.objects.filter(status='testing').all().count()
    done_count = Issue.objects.filter(status='done').all().count()
    in_processing_count = in_progress_count + testing_count

    sum = amount = 0
    for issue in Issue.objects.filter(status='done').all():
        sum += (issue.updated_at - issue.created_at).days
        amount += 1
    average_processing_time = sum / amount

    amount = 0
    for issue in Issue.objects.filter(status='done').all():
        if issue.updated_at < issue.deadline:
            amount += 1
    accuracy = round((amount / done_count) * 100, 2)
    
    issues_data = {
        'undone_count': undone_count,
        'to_do_count': to_do_count,
        'in_progress_count': in_progress_count,
        'testing_count': testing_count,
        'done_count': done_count,
        'in_processing_count': in_processing_count,
        'average_processing_time': average_processing_time,
        'accuracy': accuracy
    }

    context = {'issues_data': issues_data}
    return render(request, "main/statistics.html", context)


@group_required('Administrators', raise_exception=True)
def userManagement(request):
    users = User.objects.exclude(groups__name='Administrators').all()

    context = {'users': users}
    return render(request, "main/user-management.html", context)


def handler403(request, exception):
    context = {}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,
    minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="HandheldFriendly" content="true">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Basic SEO-->
    <title>{% block title %}Nie jesteś sam{% endblock %}</title>
    <meta name="title" content="Nie jesteś sam | Zgłoś problem, a my go rozwiążemy">
    <meta name="description" content="Zgłoś problem, a my zrobimy wszystko, co w naszej mocy, aby go jak najszybciej rozwiązać.">
    <meta name="og:image" content="{% static 'images/url-image.png' %}">
    <meta name="keywords" content="helpdesk, problem-solve">
    <!--Stylesheets-->
    {% load compress %}
    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/main.scss' %}" />
    {% endcompress %}
    <!-- Scripts -->
    {% block scripts %}
    {% compress js %}
    <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
    {% endcompress %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
    {% endblock %}
    <!--Favicon -->
    <!-- Icon made by Freepik from www.flaticon.com -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" size="32" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
</head>

<body>
    {% load has_group %}
    {% if user.is_authenticated and 'verify_email' not in request.path %}
    {% include 'main/navbar.html' %}
    {% endif %}
    <main>
        {% block content %}

        {% endblock %}
    </main>
</body>

</html>

main/templates/main/change_password.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-sm">
    <div class="row justify-content-center">
        <div class="col-md-8">
            {% for message in messages %}
            <div class="alert alert-dismissible fade show" role="alert">
                <span>{{ message }}</span>
                <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'settings' %}">
                        <span class="material-icons">arrow_back</span>
                    </a>
                    <span>Zmiana hasła</span>
                </div>
                <div class="card-body align-items-center">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row">
                            <label class="col-md-4 offset-md-1 col-form-label">{{ field.label }}</label>
                            <div class="col-md-6">
                                {{ field }}
                            </div>
                        </div>
                        {% endfor %}
                        <div class="form-group row">
                            <div class="col-md-12">
                                <button type="submit">
                                    Zmień
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/confirm_modal.html
<div class="modal fade" id="confirm-modal-{{issue.id}}" tabindex="-1" aria-labelledby="confirm-modal-label-{{issue.id}}"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirm-modal-label-{{issue.id}}">Usuwanie zgłoszenia</h5>
                <button type="button" data-bs-dismiss="modal" aria-label="Close">
                    <i class="material-icons">close</i>
                </button>
            </div>
            <div class="modal-body">
                Jesteś pewien, że chcesz usunąć zgłoszenie "{{ issue.title }}"?
            </div>
            <div class="modal-footer d-flex justify-content-center">
                <form action="{% url 'delete_issue' issue.id  %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">
                        Usuń
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

main/templates/main/create_issue.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-sm">
    <div class="row justify-content-center">
        <div class="col-md-8">
            {% for field, errors in form.errors.items %}
            <div class="alert alert-dismissible fade show" role="alert">
                <span>Błędy w polach: {{field}} {{ errors }}</span>
                <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'dashboard' %}">
                        <span class="material-icons">arrow_back</span>
                    </a>
                    <span>Dodawanie zgłoszenia</span>
                </div>
                <div class="card-body align-items-center">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="title" class="col-md-4 offset-md-1 col-form-label">Tytuł</label>
                            <div class="col-md-6">
                                <input id="id_title" type="text" class="form-control" name="title" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="description" class="col-md-4 offset-md-1 col-form-label">Opis</label>
                            <div class="col-md-6">
                                <textarea class="form-control" id="id_description" name="description"
                                    rows="3"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="deadline" class="col-md-4 offset-md-1 col-form-label">Termin</label>
                            <div class="col-md-6">
                                <input id="datetimepicker" name="deadline" type="text">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="type" class="col-md-4 offset-md-1 col-form-label">Typ zgłoszenia</label>
                            <div class="col-md-6">
                                <select class="form-select" name="type" aria-label="Wybór statusu zgłoszenia">
                                    <option value="fix">Bład</option>
                                    <option value="bug">Usterka</option>
                                    <option value="service">Naprawa</option>
                                    <option value="error">Nieprawidłowe działanie</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row d-none">
                            <label for="status" class="col-md-4 offset-md-1 col-form-label">Status</label>
                            <div class="col-md-6">
                                <select class="form-select" name="status" aria-label="Wybór przypisanego pracownika">
                                    <option value="to_do">Nierozpoczęte</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <button type="submit">
                                    Utwórz
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('#datetimepicker').datetimepicker({
        format:'Y-m-d H:i',
        step: 5,
    });
</script>
{% endblock %}

main/templates/main/dashboard.html
{% extends 'main/base.html' %}

{% block content %}
{% if not issues %}
<div class="container-center">
    <h2>Brak zgłoszeń</h2>
</div>
{% endif %}
<div class="container">
    {% for message in messages %}
    <div class="alert alert-dismissible fade show" role="alert">
        <span>{{ message }}</span>
        <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% for issue in issues %}
    <div class="card issue">
        <div class="card-header">
            <span>{{ issue.title }}</span>
            <button type="button" data-bs-toggle="modal" data-bs-target="#confirm-modal-{{ issue.id }}">
                <span class="material-icons">delete</span>
            </button>
            <button type="button" data-bs-toggle="modal" data-bs-target="#issue-modal-{{ issue.id }}">
                <span class="material-icons">edit</span>
            </button>
        </div>
        <div class="card-body">
            <span>
                <i class="material-icons">build</i>Typ zgłoszenia: 
                {% if issue.type == 'fix' %}
                Błąd
                {% elif issue.type == 'bug' %}
                Usterka
                {% elif issue.type == 'service' %}
                Naprawa
                {% elif issue.type == 'error' %}
                Nieprawidłowe działanie
                {% endif %}
            </span>
            <span>
                <i class="material-icons">report_problem</i>Osoba zgłaszająca: {{ issue.reporter }}
            </span>
            <span>
                <i class="material-icons">person</i>Przypisany pracownik: {{ issue.assignee }}
            </span>
            <span>
                <i class="material-icons">hourglass_bottom</i>Termin: {{ issue.deadline | date:"Y-m-d" }} {{ issue.deadline | time:"H:i" }}
            </span>
            <span>
                <i class="material-icons">flaky</i>Status: 
                {% if issue.status == 'done' %}
                    <span class="badge badge-success">Ukończone</span>
                {% elif issue.status == 'in_progress' %}
                    <span class="badge badge-warning">W realizacji</span>
                {% elif issue.status == 'to_do' %}
                    <span class="badge badge-danger">Nierozpoczęte</span>
                {% elif issue.status == 'testing' %}
                    <span class="badge bg-primary">Testowanie</span>
                {% endif %}
            </span>
            {% if issue.description %}
            <span><i class="material-icons">description</i>Opis: {{ issue.description }}</span>
            {% endif %}
            {% if issue.solution %}
            <span><i class="material-icons">lightbulb</i>Rozwiązanie: {{ issue.solution }}</span>
            {% endif %}
        </div>
        <div class="card-footer">
            <span><i class="material-icons">access_time</i>Utworzono: {{ issue.created_at | date:"Y-m-d" }} {{ issue.created_at | time:"H:i" }}
            </span>
            <span>
                <i class="material-icons">update</i>Zaktualizowano: {{ issue.updated_at | date:"Y-m-d" }} {{ issue.updated_at | time:"H:i" }}
            </span>
        </div>
    </div>
    {% include 'main/confirm_modal.html' %}
    {% include 'main/issue_modal.html' %}
    {% endfor %}
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-center">
    <h1>Nie jesteś sam</h1>
    <h2>Zgłoś problem, a my go rozwiążemy</h2>
    {% if user.is_authenticated %}
    <a href="{% url 'dashboard' %}">
        <button class="standalone-button" type="submit">Panel główny</button>
    </a>
    {% else %}
    <div class="buttons">
        <a href="{% url 'login' %}">
            <button type="submit">Zaloguj</button>
        </a>
    </div>
    {% endif %}
</div>
{% endblock %}

main/templates/main/password_reset.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-sm">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'login' %}">
                        <span class="material-icons">arrow_back</span>
                    </a>
                    <span>Reset hasła</span>
                </div>
                <div class="card-body align-items-center">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row">
                            <label class="col-md-4 offset-md-1 col-form-label">Adres e-mail</label>
                            <div class="col-md-6">
                                {{ field }}
                            </div>
                        </div>
                        {% endfor %}
                        <div class="form-group row">
                            <div class="col-md-12">
                                <button type="submit">
                                    Wyślij
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/password_reset_email.html
{% autoescape off %}
Otrzymałeś tę wiadomość, ponieważ zarejestrowaliśmy żądanie zmiany hasła konta użytkownika {{ user.username }} w aplikacji Nie jesteś sam ({{ site_name }}). To konto jest powiązane z Twoim adresem e-mail. Jeśli to nie Ty wykonałeś żądanie, to prosimy o zignorowanie tej wiadomości.

Aby zresetować hasło, przejdź do poniższej strony i ustaw nowe hasło:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Link resetujący hasło wygaśnie za 15 minut.

Dziękujemy za używanie naszej strony,
Zespół aplikacji Nie jesteś sam
{% endautoescape %}

main/templates/main/verification_email.html
<p>Otrzymałeś tę wiadomość, ponieważ zarejestrowaliśmy żądanie zmiany hasła konta użytkownika {{ user.username }} w aplikacji Nie jesteś sam. To konto jest powiązane z Twoim adresem e-mail. Jeśli to nie Ty wykonałeś żądanie, to prosimy o zignorowanie tej wiadomości.</p>

<p>Aby potwierdzić konto, przejdź do poniższej strony:</p>
<p>{{ link }}</p>

<p>Link potwierdzający konto wygaśnie za godzinę.</p>

<p>Dziękujemy za używanie naszej strony,</p>
<p>Zespół aplikacji Nie jesteś sam</p>

main/templates/main/verification_email_confirm.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-center">
    {% if success %}
    <h1>Witaj {{ user.username }}</h1>
    <h2>Twoje konto zostało potwierdzone.</h2>
    {% else %}
    <h1>Błąd</h1>
    <h2>Token w tym linku jest uszkodzon lub już wygasł</h2>
    {% endif %}
    <a href="{% url 'home' %}">
        <button class="standalone-button" type="submit">Strona startowa</button>
    </a>
</div>
{% endblock %}